name: Terraform CI

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4   # ✅ upgraded

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4   # ✅ upgraded

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5   # ✅ upgraded
        with:
          role-to-assume: arn:aws:iam::875141475090:role/git-trust26-policy
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false